TARGET = reset

ARDUINO_DIR = /usr/share/arduino
#ARDUINO_TOOLS_DIR = /usr/share/arduino/hardware/arduino/avr/
BOARD_TAG = uno
#ARDUINO_PORT =/dev/ttyACM0
ARDUINO_PORT =/dev/ttyUSB0

include /usr/share/arduino/Arduino.mk
